name: "🔄 Update"

# NOTE: Scheduled runs auto-deploy on changes. Manual runs deploy only if requested.
# Repository settings required: Actions → General → "Read and write permissions"

permissions: { } # No permissions at workflow level - granted per job

on:
  schedule:
    - cron: '0 8 * * MON'  # Every Monday at 8 AM UTC (1h after Nano dependabot and 1h before dev-console dependabot)
  workflow_dispatch:
    inputs:
      deploy_on_changes:
        type: boolean
        default: true
        required: false
        description: "Deploy automatically if dependency updates are successful"
      run_test:
        type: boolean
        default: true
        required: false
        description: "Run tests after updating dependencies"
      timeout_minutes:
        type: number
        default: 15
        required: false
        description: "Job timeout in minutes"

concurrency:
  group: dependency-update
  cancel-in-progress: false

jobs:
  update:
    name: "🔄 Update Dependencies"
    uses: NanoNative/nano/.github/workflows/reusable_update.yml@main
    permissions:
      contents: write      # Read repository and push changes to main
      packages: write      # Deploy to GitHub Packages (if deploy_on_changes=true)
    with:
      deploy_on_changes: ${{ inputs.deploy_on_changes || github.event_name == 'schedule' }}
      run_test: ${{ inputs.run_test != false }}
      timeout_minutes: ${{ inputs.timeout_minutes && fromJSON(inputs.timeout_minutes) || 15 }}
    secrets: inherit
